name: Release
run-name: Release

on:
  push:
    branches:
      - main

jobs:
  # ci:
  #   name: CI
  #   uses: ./.github/workflows/ci.yml
  #   with:
  #     python-versions: "['3.10', '3.11', '3.12', '3.13']"
  #     frontend-tests-folder: "tests"
  #     release: true

  call_docker_build_main:
    name: Call Docker Build Workflow for Langflow
    #needs: [ci]
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit